name: Update RSS Feed

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  update-feed:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update RSS Feed
      run: |
        echo "<?xml version=\"1.0\" encoding=\"UTF-8\" ?>
        <rss version=\"2.0\">
          <channel>
            <title>Your RSS Feed Title</title>
            <link>http://www.example.com</link>
            <description>Your RSS Feed Description</description>
            <language>en-us</language>
            <lastBuildDate>$(date -u +"%a, %d %b %Y %H:%M:%S GMT")</lastBuildDate>
            <pubDate>$(date -u +"%a, %d %b %Y %H:%M:%S GMT")</pubDate>
            <ttl>1440</ttl>

            <item>
              <title>Weekly Article</title>
              <link>http://www.example.com/article$(date -u +"%Y%m%d")</link>
              <description>This is a description of your weekly article.</description>
              <pubDate>$(date -u +"%a, %d %b %Y %H:%M:%S GMT")</pubDate>
              <guid>http://www.example.com/article$(date -u +"%Y%m%d")</guid>
            </item>

          </channel>
        </rss>" > rss_feed.xml

    - name: Commit and push changes
      env:
        TOKEN: ${{ secrets.ACTIONS_PAT }}
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add rss_feed.xml
        git commit -m "Updated RSS Feed"
        git push https://${{ secrets.ACTIONS_PAT }}@github.com/NVRCM/rss-feed.git HEAD:main
