name: Update RSS Feed  # Name of your workflow

on:
  schedule:  # Event to trigger the workflow (weekly schedule in this case)
    - cron: '0 0 * * 0'
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  update-feed:
    runs-on: ubuntu-latest  # The environment the job will run on

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Action to check out the repository

    - name: Update RSS Feed
      run: |
        echo "<?xml version=\"1.0\" encoding=\"UTF-8\" ?>
        <rss version=\"2.0\">
          <channel>
            <title>Weekly RSS Feed </title>
            <link>http://www.example.com</link>
            <description></description>
            <language>en-us</language>
            <lastBuildDate>$(date -u +"%a, %d %b %Y %H:%M:%S GMT")</lastBuildDate>
            <pubDate>$(date -u +"%a, %d %b %Y %H:%M:%S GMT")</pubDate>
            <ttl>1440</ttl>

            <item>
              <title>Frankfurter Rundschau Darmstadt</title>
              <link>https://www.fr.de/rhein-main/darmstadt</link>
              <description></description>
              <pubDate>$(date -u +"%a, %d %b %Y %H:%M:%S GMT")</pubDate>
              <guid>https://www.fr.de/rhein-main/darmstadt$(date -u +"%Y%m%d")</guid>
            </item>

            <item>
              <title>Wikipedia Topics in the News</title>
              <link>https://en.wikipedia.org/wiki/Portal:Current_events</link>
              <description></description>
              <pubDate>$(date -u +"%a, %d %b %Y %H:%M:%S GMT")</pubDate>
              <guid>https://en.wikipedia.org/wiki/Portal:Current_events$(date -u +"%Y%m%d")</guid>
            </item>

          </channel>
        </rss>" > rss_feed.xml

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add rss_feed.xml
        git commit -m "Updated RSS Feed"
        git push https://${GITHUB_TOKEN}@github.com/NVRCM/rss-feed.git HEAD:main
