name: Update RSS Feed  # Name of your workflow

on:
  schedule:  # Event to trigger the workflow (weekly schedule in this case)
    - cron: '0 0 * * 6'
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  update-feed:
    runs-on: ubuntu-latest  # The environment the job will run on

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Action to check out the repository

    - name: Update RSS Feed
      run: |
        echo "<?xml version=\"1.0\" encoding=\"UTF-8\" ?>
        <rss version=\"2.0\">
          <channel>
            <title>Weekly RSS Feed </title>
            <link>http://www.example.com</link>
            <description></description>
            <language>en-us</language>
            <lastBuildDate>$(date -u +"%a, %d %b %Y %H:%M:%S GMT")</lastBuildDate>
            <pubDate>$(date -u +"%a, %d %b %Y %H:%M:%S GMT")</pubDate>
            <ttl>1440</ttl>
            
            <item>
              <title>r/sehnsuchtpics and other subreddits</title>
              <link>https://www.reddit.com/r/sehnsuchtpics/top/?t=week</link>
              <description></description>
              <pubDate>$(date -u +"%a, %d %b %Y %H:%M:%S GMT")</pubDate>
              <guid>https://www.reddit.com/r/sehnsuchtpics/top/?t=week$(date -u +"%Y%m%d")</guid>
            </item>
            
            <item>
              <title>Deutschlandfunk Wochenrückblick</title>
              <link>https://www.ard-text.de/mobil/750</link>
              <description></description>
              <pubDate>$(date -u +"%a, %d %b %Y %H:%M:%S GMT")</pubDate>
              <guid>https://www.ard-text.de/mobil/750$(date -u +"%Y%m%d")</guid>
            </item>
            
            <item>
              <title>Wikipedia Topics in the News</title>
              <link>https://en.wikipedia.org/wiki/Portal:Current_events</link>
              <description></description>
              <pubDate>$(date -u +"%a, %d %b %Y %H:%M:%S GMT")</pubDate>
              <guid>https://en.wikipedia.org/wiki/Portal:Current_events$(date -u +"%Y%m%d")</guid>
            </item>
            
            <item>
              <title>Frankfurter Rundschau</title>
              <link>https://www.fr.de/rhein-main/darmstadt</link>
              <description></description>
              <pubDate>$(date -u +"%a, %d %b %Y %H:%M:%S GMT")</pubDate>
              <guid>https://www.fr.de/rhein-main/$(date -u +"%Y%m%d")</guid>
            </item>
            
            <item>
              <title>MIT Technology Review</title>
              <link>https://www.technologyreview.com/</link>
              <description></description>
              <pubDate>$(date -u +"%a, %d %b %Y %H:%M:%S GMT")</pubDate>
              <guid>https://www.technologyreview.com/$(date -u +"%Y%m%d")</guid>
            </item>

            <item>
              <title>Lifehacker (Junk)</title>
              <link>https://lifehacker.com/</link>
              <description></description>
              <pubDate>$(date -u +"%a, %d %b %Y %H:%M:%S GMT")</pubDate>
              <guid>https://lifehacker.com/$(date -u +"%Y%m%d")</guid>
            </item>

            <item>
              <title>https://www.test.de/archiv/</title>
              <link>https://lifehacker.com/</link>
              <description></description>
              <pubDate>$(date -u +"%a, %d %b %Y %H:%M:%S GMT")</pubDate>
              <guid>https://www.test.de/archiv/$(date -u +"%Y%m%d")</guid>
            </item>

            <item>
              <title>Wikipedia 2024 in Science</title>
              <link>https://en.m.wikipedia.org/wiki/2024_in_science</link>
              <description></description>
              <pubDate>$(date -u +"%a, %d %b %Y %H:%M:%S GMT")</pubDate>
              <guid>https://en.m.wikipedia.org/wiki/2024_in_science$(date -u +"%Y%m%d")</guid>
            </item>

            <item>
              <title>Wikipedia 2024 in Science</title>
              <link>https://en.m.wikipedia.org/wiki/2024_in_science</link>
              <description></description>
              <pubDate>$(date -u +"%a, %d %b %Y %H:%M:%S GMT")</pubDate>
              <guid>https://en.m.wikipedia.org/wiki/2024_in_science$(date -u +"%Y%m%d")</guid>
            </item>

            <item>
              <title>Wikipedia 2024 in Germany</title>
              <link>https://en.m.wikipedia.org/wiki/2024_in_Germany</link>
              <description></description>
              <pubDate>$(date -u +"%a, %d %b %Y %H:%M:%S GMT")</pubDate>
              <guid>https://en.m.wikipedia.org/wiki/2024_in_Germany$(date -u +"%Y%m%d")</guid>
            </item>

            <item>
              <title>Wikipedia 2024</title>
              <link>https://en.m.wikipedia.org/wiki/2024</link>
              <description></description>
              <pubDate>$(date -u +"%a, %d %b %Y %H:%M:%S GMT")</pubDate>
              <guid>https://en.m.wikipedia.org/wiki/2024$(date -u +"%Y%m%d")</guid>
            </item>

            <item>
              <title>logo!</title>
              <link>https://www.zdf.de/kinder/logo</link>
              <description></description>
              <pubDate>$(date -u +"%a, %d %b %Y %H:%M:%S GMT")</pubDate>
              <guid>https://www.zdf.de/kinder/logo$(date -u +"%Y%m%d")</guid>
            </item>

            <item>
              <title>Verbraucherzentrale</title>
              <link>https://www.verbraucherzentrale.de/</link>
              <description></description>
              <pubDate>$(date -u +"%a, %d %b %Y %H:%M:%S GMT")</pubDate>
              <guid>https://www.verbraucherzentrale.de/$(date -u +"%Y%m%d")</guid>
            </item>

          </channel>
        </rss>" > rss_feed.xml

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add rss_feed.xml
        git commit -m "Updated RSS Feed"
        git push https://${GITHUB_TOKEN}@github.com/NVRCM/rss-feed.git HEAD:main
